# Imagen oficial de SonarQube de Bitnami, versión más reciente
FROM sonarqube:2026.2.1-developer

# Puerto principal de SonarQube (interfaz web)
EXPOSE 9000

# Puerto de Elasticsearch interno (componente que SonarQube usa internamente)
EXPOSE 9001